<a href="https://colab.research.google.com/github/Saisuhaschandra/AIML-LAB/blob/main/LAB_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#lists
my_list = [1, 2, 3,"hello", "world"]
print(my_list[0])
print(my_list[3])


1
hello


In [ ]:
#arrays
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[1:3])

[2 3]


In [ ]:
#identifing their type()

type(arr)

numpy.ndarray

In [ ]:
#operations
import numpy as np
arr1=np.array([5,6,7])
arr2=np.array([1,2,3])
arr3=arr1+arr2
print("add")
print(arr3)
arr3=arr1-arr2
print("sub")
print(arr3)
arr3=arr1*arr2
print("mul")
print(arr3)

arr3=arr1 ** arr2
print("power")
print(arr3)

add
[ 6  8 10]
sub
[4 4 4]
mul
[ 5 12 21]
power
[  5  36 343]


In [ ]:
#addition with textual output
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
output="addition of two arrays: array1 + array2 =",list(arr1)+arr2
print(output)


('addition of two arrays: array1 + array2 =', array([5, 7, 9]))
